[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "spaces"
author = "anthony"
author-email = "anthonyd-m@live.com"
classifiers = ["License :: OSI Approved :: MIT License"]

